import { formatArchiveName } from '../ui/format.js';

export function commitMessageCandidates(state) {
  const values = {
    llm: cleanCommitMessage(state.run?.llm?.commitMessage),
    metadata: cleanCommitMessage(state.archiveMetadata?.commitMessage),
    fixed: state.workflow?.git?.messageStrategy === 'fixed'
      ? cleanCommitMessage(renderTemplate(state.workflow.git.fixedMessage, state))
      : '',
    generated: state.workflow?.git?.messageStrategy === 'archive'
      ? `Apply ${formatArchiveName(state.run.archivePath)}`
      : `zipflow: apply ${state.run.id}`,
  };
  const definitions = {
    llm: {
      label: 'Local LLM',
      detail: state.run?.llm?.model
        ? `Generated by ${state.run.llm.provider} · ${state.run.llm.model}`
        : 'Generated by the configured local model.',
    },
    metadata: {
      label: 'Archive message',
      detail: state.archiveMetadata?.commitMessageSource
        ? `Read from ${state.archiveMetadata.commitMessageSource}`
        : 'Read from archive metadata.',
    },
    fixed: { label: 'Workflow template', detail: 'Rendered from the workflow commit-message template.' },
    generated: { label: 'Generated message', detail: 'Generated deterministically for this run.' },
  };
  const strategy = state.workflow?.git?.messageStrategy;
  const preferred = strategy === 'metadata'
    ? 'metadata'
    : strategy === 'fixed'
      ? 'fixed'
      : strategy === 'archive'
        ? 'generated'
        : 'llm';
  const order = [preferred, 'llm', 'metadata', 'fixed', 'generated'];
  const seenIds = new Set();
  const seenMessages = new Set();
  const result = [];
  for (const id of order) {
    const message = values[id];
    if (!message || seenIds.has(id) || seenMessages.has(message)) continue;
    seenIds.add(id);
    seenMessages.add(message);
    result.push({ id, message, ...definitions[id] });
  }
  return result;
}

export function defaultCommitMessage(state) {
  return commitMessageCandidates(state)[0]?.message || `zipflow: apply ${state.run.id}`;
}

export function commitMessageEditorInitialValue(state) {
  if (state.workflow.git.messageStrategy === 'llm' && !cleanCommitMessage(state.run.llm?.commitMessage)) return '';
  return defaultCommitMessage(state);
}

function cleanCommitMessage(value) {
  if (typeof value !== 'string') return '';
  const message = value.trim();
  if (!message) return '';
  if (/^[\[{]/.test(message)) {
    try {
      JSON.parse(message);
      return '';
    } catch {
      // A normal commit message may legitimately begin with a bracket.
    }
  }
  return message;
}

function renderTemplate(template, state) {
  const now = new Date();
  return String(template)
    .replaceAll('{runId}', state.run.id)
    .replaceAll('{archiveName}', formatArchiveName(state.run.archivePath))
    .replaceAll('{projectName}', state.project.name)
    .replaceAll('{date}', now.toISOString().slice(0, 10))
    .replaceAll('{time}', now.toTimeString().slice(0, 8));
}
